pipeline {
    agent any

    environment {
        IMAGE_TAG = "${BUILD_ID}" // Uses Jenkins build ID as the tag
        DOCKER_REPO = "gopi93/node-api"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_REPO:$IMAGE_TAG .'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push $DOCKER_REPO:$IMAGE_TAG'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 3000:3000 $DOCKER_REPO:$IMAGE_TAG'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying to production server..."'
            }
        }
    }
}
