pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'npm test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    sh 'docker build -t node-api:20250421-1130-abc123 .'
                }
            }
        }
        stage('Docker Push') {
            steps {
                script {
                    sh 'docker login -u {gopit93} -p {Gopi__t93}'
                    sh 'docker push node-api:20250421-1130-abc123'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -d -p 3000:3000 node-api:20250421-1130-abc123'
                }
            }
        }
    }
}